name: echochat_backend
description: Dart Frog backend for EchoChat demo.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dart_frog: ^1.2.0
  uuid: ^4.5.1

dev_dependencies:
  dart_frog_cli: ^1.2.14
  lints: ^5.1.1
  test: ^1.25.8
