import 'package:core/core.dart';
import 'package:flutter/material.dart';

class AppThemeColor extends ThemeColor {
  AppThemeColor({
    super.primary = const Color(0xFF2563EB),
    super.primaryVariant = const Color(0xFF1D4ED8),
    super.secondary = const Color(0xFFEFF6FF),
    super.secondaryVariant = const Color(0xFFDCEBFF),
    super.surface = Colors.white,
    super.background = const Color(0xFFF8FAFC),
    super.appbarBackgroundColor = Colors.white,
    super.appbarForegroundColor = const Color(0xFF0F172A),
    super.scaffoldBackgroundColor = const Color(0xFFF8FAFC),
    super.cardBackground = Colors.white,
    super.canvasColor = Colors.white,
    super.borderColor = const Color(0xFFE2E8F0),
    super.dividerColor = const Color(0xFFE2E8F0),
    super.disableColor = const Color(0xFFCBD5E1),
    super.shadowColor = const Color(0xFF94A3B8),
    super.brightness = Brightness.light,
    super.elevatedBtnForegroundColor = Colors.white,
    super.elevatedBtnBackgroundDisableColor = const Color(0xFFE2E8F0),
    super.elevatedBtnForegroundDisableColor = const Color(0xFF94A3B8),
    super.schemeAction = const Color(0xFF2563EB),
    super.outlineButtonColor = const Color(0xFF2563EB),
    super.outlineButtonDisableColor = const Color(0xFF94A3B8),
    super.chipBackgroundColor = Colors.white,
    super.chipBorderColor = const Color(0xFFE2E8F0),
    super.chipSelectedColor = const Color(0xFFEFF6FF),
    super.chipLabelColor = const Color(0xFF334155),
    super.displayText = const Color(0xFF0F172A),
    super.headlineText = const Color(0xFF0F172A),
    super.titleText = const Color(0xFF0F172A),
    super.bodyText = const Color(0xFF334155),
    super.labelText = const Color(0xFF64748B),
  });
}

class AppDarkThemeColor extends ThemeColor {
  AppDarkThemeColor({
    super.primary = const Color(0xFF60A5FA),
    super.primaryVariant = const Color(0xFF3B82F6),
    super.secondary = const Color(0xFF172554),
    super.secondaryVariant = const Color(0xFF1E3A8A),
    super.surface = const Color(0xFF111827),
    super.background = const Color(0xFF020617),
    super.appbarForegroundColor = const Color(0xFFE2E8F0),
    super.appbarBackgroundColor = const Color(0xFF0F172A),
    super.scaffoldBackgroundColor = const Color(0xFF020617),
    super.cardBackground = const Color(0xFF0F172A),
    super.canvasColor = const Color(0xFF111827),
    super.borderColor = const Color(0xFF334155),
    super.dividerColor = const Color(0xFF1E293B),
    super.disableColor = const Color(0xFF475569),
    super.shadowColor = Colors.black,
    super.brightness = Brightness.dark,
    super.schemeAction = const Color(0xFF60A5FA),
    super.outlineButtonColor = const Color(0xFF93C5FD),
    super.chipBackgroundColor = const Color(0xFF111827),
    super.chipBorderColor = const Color(0xFF334155),
    super.chipSelectedColor = const Color(0xFF1E3A8A),
    super.chipLabelColor = const Color(0xFFE2E8F0),
    super.displayText = const Color(0xFFF8FAFC),
    super.headlineText = const Color(0xFFF8FAFC),
    super.titleText = const Color(0xFFF8FAFC),
    super.bodyText = const Color(0xFFCBD5E1),
    super.labelText = const Color(0xFF94A3B8),
  });
}
